name: Daily Google Sheets Backup

on:
  schedule:
    - cron: "55 17 * * *"   # প্রতিদিন রাত 11:55 Asia/Dhaka (UTC+6 => 17:55 UTC)
  workflow_dispatch:        # চাইলে manual trigger করা যাবে

jobs:
  backup:
    runs-on: ubuntu-latest
    concurrency:
      group: gsheet-daily-backup
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run backup script
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: node backup.js