name: Daily Google Sheets Backup

on:
  schedule:
    - cron: '0 10 * * *'   # Runs daily at 16:00 Asia/Dhaka (UTC+6 -> 10:00 UTC)
  workflow_dispatch:        # Manual trigger possible

jobs:
  backup:
    runs-on: ubuntu-latest
    concurrency:
      group: gsheet-daily-backup
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run backup script
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}  # Fixed line
        run: node backup.js